"""
Frontend Formatter

Converts processed pipeline output to the format expected by
the news recommendation demo's newsData array in index.html.
"""

import json
import os
import logging
from datetime import datetime, timedelta, timezone
from typing import Any

logger = logging.getLogger("formatter")


def generate_time_ago() -> list[str]:
    """Return a list of relative time strings for articles."""
    return [
        "30 minutes ago",
        "1 hour ago",
        "2 hours ago",
        "3 hours ago",
        "4 hours ago",
        "5 hours ago",
        "6 hours ago",
        "8 hours ago",
        "10 hours ago",
        "12 hours ago",
        "14 hours ago",
        "16 hours ago",
        "18 hours ago",
        "20 hours ago",
        "22 hours ago",
        "1 day ago",
    ]


def generate_thumbnail_urls(count: int) -> list[str]:
    """Generate picsum.photos thumbnail URLs for articles."""
    seeds = [
        "politics-election",
        "politics-policy",
        "politics-diplomacy",
        "politics-natsec",
        "politics-immigration",
        "politics-governance",
        "politics-campaign",
        "politics-legislation",
        "politics-foreign",
        "politics-defense",
        "politics-border",
        "politics-congress",
        "politics-whitehouse",
        "politics-senate",
        "politics-trade",
        "politics-vote",
    ]
    urls = []
    for i in range(count):
        seed = seeds[i % len(seeds)]
        urls.append(f"https://picsum.photos/seed/{seed}{i}/360/240")
    return urls


def format_for_frontend(
    articles: list[dict[str, Any]],
    output_path: str = "",
) -> str:
    """
    Convert pipeline-processed articles to the frontend newsData format
    and write a JS snippet that can be injected into index.html.

    Returns the generated JavaScript string.
    """
    time_labels = generate_time_ago()
    thumbnails = generate_thumbnail_urls(len(articles))

    formatted: list[dict[str, Any]] = []
    for i, art in enumerate(articles[:20]):  # Max 20 for frontend
        perspectives = art.get("perspectives", {})
        item = {
            "id": i + 1,
            "title": art.get("title", ""),
            "summary": art.get("summary", ""),
            "category": art.get("category", "Politics"),
            "subtopic": art.get("subtopic", "Policy"),
            "tags": art.get("tags", ["politics"]),
            "source": art.get("source", "News Wire"),
            "time": time_labels[i % len(time_labels)],
            "thumb": thumbnails[i % len(thumbnails)],
            "url": art.get("url", ""),
            "perspectives": {
                "left": {
                    "headline": perspectives.get("left", {}).get("headline", art.get("title", "")),
                    "source": perspectives.get("left", {}).get("source", "The Progressive Times"),
                    "summary": perspectives.get("left", {}).get("summary", ""),
                },
                "center": {
                    "headline": perspectives.get("center", {}).get("headline", art.get("title", "")),
                    "source": perspectives.get("center", {}).get("source", "Associated Press"),
                    "summary": perspectives.get("center", {}).get("summary", ""),
                },
                "right": {
                    "headline": perspectives.get("right", {}).get("headline", art.get("title", "")),
                    "source": perspectives.get("right", {}).get("source", "The National Review"),
                    "summary": perspectives.get("right", {}).get("summary", ""),
                },
            },
        }
        formatted.append(item)

    js = "// AUTO-GENERATED by news_fetcher pipeline\n"
    js += f"// Generated at: {datetime.now(timezone.utc).isoformat()}\n"
    js += f"// Article count: {len(formatted)}\n\n"
    js += "const liveNewsData = " + json.dumps(formatted, indent=2, ensure_ascii=False) + ";\n"

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(js)
        logger.info("Frontend data written to %s", output_path)

    return js


def generate_full_html(
    articles: list[dict[str, Any]],
    template_path: str,
    output_path: str,
) -> str:
    """
    Inject live news data into the index.html template and write the result.

    Replaces `const newsData = [` with the generated data, so the page
    renders the fresh articles fetched by the pipeline.
    """
    if not os.path.exists(template_path):
        raise FileNotFoundError(f"Template not found: {template_path}")

    with open(template_path, "r", encoding="utf-8") as f:
        html = f.read()

    # Build the replacement data block
    time_labels = generate_time_ago()
    thumbnails = generate_thumbnail_urls(len(articles))

    formatted: list[dict[str, Any]] = []
    for i, art in enumerate(articles[:20]):
        perspectives = art.get("perspectives", {})
        formatted.append({
            "id": i + 1,
            "title": art.get("title", ""),
            "summary": art.get("summary", ""),
            "category": art.get("category", "Politics"),
            "subtopic": art.get("subtopic", "Policy"),
            "tags": art.get("tags", ["politics"]),
            "source": art.get("source", "News Wire"),
            "time": time_labels[i % len(time_labels)],
            "thumb": thumbnails[i % len(thumbnails)],
            "url": art.get("url", ""),
            "perspectives": {
                "left": {
                    "headline": perspectives.get("left", {}).get("headline", art.get("title", "")),
                    "source": perspectives.get("left", {}).get("source", "The Progressive Times"),
                    "summary": perspectives.get("left", {}).get("summary", ""),
                },
                "center": {
                    "headline": perspectives.get("center", {}).get("headline", art.get("title", "")),
                    "source": perspectives.get("center", {}).get("source", "Associated Press"),
                    "summary": perspectives.get("center", {}).get("summary", ""),
                },
                "right": {
                    "headline": perspectives.get("right", {}).get("headline", art.get("title", "")),
                    "source": perspectives.get("right", {}).get("source", "The National Review"),
                    "summary": perspectives.get("right", {}).get("summary", ""),
                },
            },
        })

    new_data_block = "const newsData = " + json.dumps(formatted, indent=2, ensure_ascii=False) + ";"

    # Find and replace the data array
    marker = "const newsData = ["
    start = html.index(marker)
    # Find the matching closing ]; (first occurrence after the opening)
    depth = 0
    end = start
    for i in range(start, len(html)):
        if html[i] == "[":
            depth += 1
        elif html[i] == "]":
            depth -= 1
            if depth == 0:
                # Now find the semicolon
                j = i + 1
                while j < len(html) and html[j] != ";":
                    j += 1
                end = j + 1
                break

    new_html = html[:start] + new_data_block + html[end:]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(new_html)

    logger.info("Generated full HTML: %s", output_path)
    return output_path
